from django.core.management.base import BaseCommand

from accounts.models import User
from candidates.models import CandidateProfile
from jobs.models import JobApplication, JobPosting


PASSWORD = "password123"


class Command(BaseCommand):
    help = "Create demo employers, candidates, jobs, and applications."

    def handle(self, *args, **options):
        employers = self.create_employers()
        candidates = self.create_candidates()
        jobs = self.create_jobs(employers)
        self.create_applications(jobs, candidates)

        self.stdout.write(
            self.style.SUCCESS(
                "Demo data ready: 3 employers, 10 candidates, 50 jobs, and 9 applications. "
                f"Password for all demo users: {PASSWORD}"
            )
        )

    def create_user(self, email, full_name, role):
        user, _ = User.objects.get_or_create(
            email=email,
            defaults={
                "username": email,
                "full_name": full_name,
                "role": role,
            },
        )
        user.username = email
        user.full_name = full_name
        user.role = role
        user.set_password(PASSWORD)
        user.save()
        return user

    def create_employers(self):
        employers = {}

        data = [
            ("hiring@northwind.io", "Northwind Labs"),
            ("talent@brightpath.com", "BrightPath Digital"),
            ("recruitment@cloudnova.ai", "CloudNova AI"),
        ]

        for email, full_name in data:
            employers[email] = self.create_user(email, full_name, User.Role.EMPLOYER)

        return employers

    def create_candidates(self):
        candidates = {}

        data = [
            {
                "email": "aarav.mehta@example.com",
                "full_name": "Aarav Mehta",
                "location": "Singapore",
                "headline": "Senior Full-Stack Engineer",
                "bio": "Six years building React and Django products.",
                "education": CandidateProfile.Education.MASTER,
                "major": "Computer Science",
                "years_experience": 6,
                "skills": ["React", "TypeScript", "Django", "PostgreSQL", "Docker", "Redis"],
            },
            {
                "email": "sophia.chen@example.com",
                "full_name": "Sophia Chen",
                "location": "Sydney",
                "headline": "Frontend Engineer",
                "bio": "Frontend developer focused on accessible React interfaces.",
                "education": CandidateProfile.Education.BACHELOR,
                "major": "Software Engineering",
                "years_experience": 3,
                "skills": ["React", "TypeScript", "Tailwind CSS", "Vite", "Figma"],
            },
            {
                "email": "liam.tan@example.com",
                "full_name": "Liam Tan",
                "location": "Melbourne",
                "headline": "Backend Developer",
                "bio": "Backend developer experienced in Django APIs and databases.",
                "education": CandidateProfile.Education.BACHELOR,
                "major": "Information Technology",
                "years_experience": 4,
                "skills": ["Python", "Django", "REST API", "PostgreSQL", "JWT", "Docker"],
            },
            {
                "email": "maya.kumar@example.com",
                "full_name": "Maya Kumar",
                "location": "Singapore",
                "headline": "Data Analyst",
                "bio": "Data analyst experienced in dashboards and business insights.",
                "education": CandidateProfile.Education.MASTER,
                "major": "Data Science",
                "years_experience": 5,
                "skills": ["Python", "SQL", "Power BI", "Tableau", "Machine Learning"],
            },
            {
                "email": "daniel.park@example.com",
                "full_name": "Daniel Park",
                "location": "Brisbane",
                "headline": "Cloud Engineer",
                "bio": "Cloud engineer working with containers, CI/CD, and AWS.",
                "education": CandidateProfile.Education.BACHELOR,
                "major": "Computer Engineering",
                "years_experience": 5,
                "skills": ["AWS", "Docker", "Kubernetes", "Terraform", "Linux", "CI/CD"],
            },
            {
                "email": "emily.wong@example.com",
                "full_name": "Emily Wong",
                "location": "Sydney",
                "headline": "UX Designer",
                "bio": "UX designer creating wireframes, prototypes, and accessible interfaces.",
                "education": CandidateProfile.Education.BACHELOR,
                "major": "Interaction Design",
                "years_experience": 4,
                "skills": ["Figma", "User Research", "Wireframing", "Prototyping", "Accessibility"],
            },
            {
                "email": "noah.smith@example.com",
                "full_name": "Noah Smith",
                "location": "Perth",
                "headline": "Junior Software Developer",
                "bio": "Junior developer with web application and database experience.",
                "education": CandidateProfile.Education.DIPLOMA,
                "major": "Web Development",
                "years_experience": 1,
                "skills": ["JavaScript", "React", "Node.js", "SQLite", "HTML", "CSS"],
            },
            {
                "email": "olivia.brown@example.com",
                "full_name": "Olivia Brown",
                "location": "Adelaide",
                "headline": "AI Engineer",
                "bio": "AI engineer building recommendation and NLP prototypes.",
                "education": CandidateProfile.Education.MASTER,
                "major": "Artificial Intelligence",
                "years_experience": 4,
                "skills": ["Python", "Machine Learning", "NLP", "FastAPI", "Pandas", "TensorFlow"],
            },
            {
                "email": "ethan.nguyen@example.com",
                "full_name": "Ethan Nguyen",
                "location": "Canberra",
                "headline": "Cybersecurity Analyst",
                "bio": "Security analyst focused on secure systems and vulnerability assessment.",
                "education": CandidateProfile.Education.BACHELOR,
                "major": "Cybersecurity",
                "years_experience": 3,
                "skills": ["Security", "Python", "Linux", "Risk Assessment", "Networking", "OWASP"],
            },
            {
                "email": "ava.martin@example.com",
                "full_name": "Ava Martin",
                "location": "Remote",
                "headline": "Product Manager",
                "bio": "Product manager translating user needs into agile delivery plans.",
                "education": CandidateProfile.Education.BACHELOR,
                "major": "Business Information Systems",
                "years_experience": 6,
                "skills": ["Agile", "Product Strategy", "User Stories", "Analytics", "Stakeholder Management"],
            },
        ]

        for item in data:
            user = self.create_user(item["email"], item["full_name"], User.Role.CANDIDATE)

            profile, _ = CandidateProfile.objects.update_or_create(
                user=user,
                defaults={
                    "full_name": item["full_name"],
                    "email": item["email"],
                    "location": item["location"],
                    "headline": item["headline"],
                    "bio": item["bio"],
                    "education": item["education"],
                    "major": item["major"],
                    "years_experience": item["years_experience"],
                    "skills": item["skills"],
                },
            )

            candidates[item["email"]] = profile

        return candidates

    def create_jobs(self, employers):
        jobs = {}

        data = [
            # ── Northwind Labs ────────────────────────────────────────────────
            {
                "employer": "hiring@northwind.io",
                "title": "Senior Full-Stack Engineer",
                "company": "Northwind Labs",
                "description": "Build analytics features across React, Django, and PostgreSQL.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["React", "TypeScript", "Django", "PostgreSQL", "Docker"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 9000,
                "salary_max": 13000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Backend API Developer",
                "company": "Northwind Labs",
                "description": "Develop secure REST APIs and authentication workflows.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Python", "Django", "REST API", "JWT", "PostgreSQL"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 7500,
                "salary_max": 11000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Cloud DevOps Engineer",
                "company": "Northwind Labs",
                "description": "Maintain cloud infrastructure and deployment pipelines.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 8500,
                "salary_max": 12500,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Platform Engineer",
                "company": "Northwind Labs",
                "description": "Design and operate internal developer platforms and tooling.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Kubernetes", "Terraform", "Go", "Linux", "CI/CD"],
                "min_years_experience": 5,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 10000,
                "salary_max": 14000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Site Reliability Engineer",
                "company": "Northwind Labs",
                "description": "Own uptime, incident response, and observability for production services.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Linux", "Python", "Prometheus", "Grafana", "AWS"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 9500,
                "salary_max": 13500,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "iOS Developer",
                "company": "Northwind Labs",
                "description": "Build and ship features on our Swift-based iOS analytics app.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Swift", "SwiftUI", "Xcode", "REST API", "Git"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Melbourne",
                "salary_min": 8000,
                "salary_max": 11500,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Android Developer",
                "company": "Northwind Labs",
                "description": "Develop new features in Kotlin for our Android productivity app.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Kotlin", "Jetpack Compose", "Android SDK", "REST API", "Git"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Melbourne",
                "salary_min": 8000,
                "salary_max": 11500,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "QA Automation Engineer",
                "company": "Northwind Labs",
                "description": "Build end-to-end test suites and integrate them into CI pipelines.",
                "required_education": JobPosting.Education.DIPLOMA,
                "required_skills": ["Pytest", "Selenium", "Python", "CI/CD", "Git"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 6500,
                "salary_max": 9500,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Technical Lead",
                "company": "Northwind Labs",
                "description": "Guide a cross-functional squad delivering backend and data features.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Python", "Django", "PostgreSQL", "System Design", "Mentoring"],
                "min_years_experience": 7,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 13000,
                "salary_max": 18000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Database Administrator",
                "company": "Northwind Labs",
                "description": "Manage, tune, and migrate PostgreSQL clusters supporting our SaaS platform.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["PostgreSQL", "SQL", "Linux", "Backup & Recovery", "Performance Tuning"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.ON_SITE,
                "location": "Singapore",
                "salary_min": 8000,
                "salary_max": 11000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Solutions Architect",
                "company": "Northwind Labs",
                "description": "Design scalable cloud solutions and support pre-sales technical engagements.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["AWS", "System Design", "Microservices", "Terraform", "Communication"],
                "min_years_experience": 6,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 12000,
                "salary_max": 17000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Developer Advocate",
                "company": "Northwind Labs",
                "description": "Create tutorials, demos, and community content for our developer API.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Python", "REST API", "Technical Writing", "Public Speaking", "Git"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 8000,
                "salary_max": 11000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Security Engineer",
                "company": "Northwind Labs",
                "description": "Conduct security reviews, threat modelling, and vulnerability remediation.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Security", "Python", "OWASP", "Linux", "Penetration Testing"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 10000,
                "salary_max": 14000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Embedded Systems Engineer",
                "company": "Northwind Labs",
                "description": "Develop firmware for IoT edge devices that feed data into our platform.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["C", "C++", "RTOS", "Embedded Linux", "MQTT"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.ON_SITE,
                "location": "Singapore",
                "salary_min": 8500,
                "salary_max": 12000,
            },
            {
                "employer": "hiring@northwind.io",
                "title": "Engineering Manager",
                "company": "Northwind Labs",
                "description": "Lead and grow a team of 6–8 engineers across two product squads.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["People Management", "Agile", "System Design", "Python", "Roadmapping"],
                "min_years_experience": 8,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 15000,
                "salary_max": 20000,
            },
            # ── BrightPath Digital ────────────────────────────────────────────
            {
                "employer": "talent@brightpath.com",
                "title": "Frontend React Developer",
                "company": "BrightPath Digital",
                "description": "Create responsive dashboards and reusable UI components.",
                "required_education": JobPosting.Education.DIPLOMA,
                "required_skills": ["React", "TypeScript", "Tailwind CSS", "Vite"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 6500,
                "salary_max": 9500,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "UX/UI Designer",
                "company": "BrightPath Digital",
                "description": "Design user flows, prototypes, and accessible interfaces.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Figma", "User Research", "Wireframing", "Prototyping", "Accessibility"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.ON_SITE,
                "location": "Melbourne",
                "salary_min": 6000,
                "salary_max": 9000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Junior Web Developer",
                "company": "BrightPath Digital",
                "description": "Support React pages, Node.js services, and SQLite-backed tools.",
                "required_education": JobPosting.Education.DIPLOMA,
                "required_skills": ["JavaScript", "React", "Node.js", "SQLite", "CSS"],
                "min_years_experience": 1,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 4500,
                "salary_max": 6500,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Product Manager",
                "company": "BrightPath Digital",
                "description": "Lead roadmap planning and agile delivery for digital products.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Agile", "Product Strategy", "User Stories", "Analytics"],
                "min_years_experience": 5,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Adelaide",
                "salary_min": 8000,
                "salary_max": 12000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Vue.js Developer",
                "company": "BrightPath Digital",
                "description": "Build interactive client portals using Vue 3 and Pinia.",
                "required_education": JobPosting.Education.DIPLOMA,
                "required_skills": ["Vue.js", "JavaScript", "Pinia", "REST API", "CSS"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Brisbane",
                "salary_min": 6000,
                "salary_max": 9000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Full-Stack JavaScript Developer",
                "company": "BrightPath Digital",
                "description": "Deliver features end-to-end across Next.js and Express microservices.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Next.js", "Node.js", "TypeScript", "PostgreSQL", "Docker"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 7500,
                "salary_max": 11000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Motion Designer",
                "company": "BrightPath Digital",
                "description": "Produce animations and micro-interactions for web and mobile products.",
                "required_education": JobPosting.Education.DIPLOMA,
                "required_skills": ["After Effects", "Lottie", "Figma", "CSS Animation", "Storybook"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.ON_SITE,
                "location": "Sydney",
                "salary_min": 5500,
                "salary_max": 8000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Content Strategist",
                "company": "BrightPath Digital",
                "description": "Plan and write content for product onboarding, help docs, and marketing.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Content Strategy", "Copywriting", "SEO", "CMS", "Analytics"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Melbourne",
                "salary_min": 5500,
                "salary_max": 8000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "SEO & Growth Analyst",
                "company": "BrightPath Digital",
                "description": "Drive organic growth through technical SEO audits and A/B testing.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["SEO", "Google Analytics", "Python", "A/B Testing", "SQL"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 5500,
                "salary_max": 8500,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Accessibility Engineer",
                "company": "BrightPath Digital",
                "description": "Audit and remediate WCAG compliance across our web and mobile products.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Accessibility", "HTML", "CSS", "React", "ARIA"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 7000,
                "salary_max": 10000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Design Systems Lead",
                "company": "BrightPath Digital",
                "description": "Own and evolve our component library and design token system.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Figma", "React", "Storybook", "Tailwind CSS", "Design Tokens"],
                "min_years_experience": 5,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 10000,
                "salary_max": 14000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Scrum Master",
                "company": "BrightPath Digital",
                "description": "Facilitate sprints, retrospectives, and delivery ceremonies for two squads.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Scrum", "Agile", "Jira", "Facilitation", "Stakeholder Management"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Melbourne",
                "salary_min": 7000,
                "salary_max": 10000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Technical Project Manager",
                "company": "BrightPath Digital",
                "description": "Coordinate cross-team deliverables for large client integration projects.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Project Management", "Agile", "Risk Management", "Jira", "Stakeholder Management"],
                "min_years_experience": 5,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Adelaide",
                "salary_min": 9000,
                "salary_max": 13000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "API Integration Specialist",
                "company": "BrightPath Digital",
                "description": "Connect third-party SaaS platforms to our core product via REST and webhooks.",
                "required_education": JobPosting.Education.DIPLOMA,
                "required_skills": ["REST API", "Webhooks", "Node.js", "OAuth", "Postman"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 6000,
                "salary_max": 9000,
            },
            {
                "employer": "talent@brightpath.com",
                "title": "Business Analyst",
                "company": "BrightPath Digital",
                "description": "Gather requirements, map business processes, and write detailed specifications.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Requirements Analysis", "SQL", "Process Mapping", "Jira", "Communication"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Brisbane",
                "salary_min": 6500,
                "salary_max": 9500,
            },
            # ── CloudNova AI ──────────────────────────────────────────────────
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Machine Learning Engineer",
                "company": "CloudNova AI",
                "description": "Build ML services for recommendations and NLP processing.",
                "required_education": JobPosting.Education.MASTER,
                "required_skills": ["Python", "Machine Learning", "NLP", "TensorFlow", "Pandas"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 8500,
                "salary_max": 13000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Data Analyst",
                "company": "CloudNova AI",
                "description": "Analyse product data and build dashboards for hiring insights.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Python", "SQL", "Power BI", "Tableau"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 6000,
                "salary_max": 9000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Cybersecurity Analyst",
                "company": "CloudNova AI",
                "description": "Review system risks and improve secure development practices.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Security", "Python", "Linux", "Networking", "OWASP"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.ON_SITE,
                "location": "Canberra",
                "salary_min": 7000,
                "salary_max": 10000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "AI Research Engineer",
                "company": "CloudNova AI",
                "description": "Prototype and evaluate large language model integrations for product features.",
                "required_education": JobPosting.Education.MASTER,
                "required_skills": ["Python", "PyTorch", "Transformers", "LLMs", "Research"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 11000,
                "salary_max": 16000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "MLOps Engineer",
                "company": "CloudNova AI",
                "description": "Manage ML model training pipelines, versioning, and production serving.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Python", "MLflow", "Docker", "Kubernetes", "AWS"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 9000,
                "salary_max": 13000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Data Engineer",
                "company": "CloudNova AI",
                "description": "Design and maintain data pipelines feeding our analytics and ML systems.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Python", "Apache Spark", "Airflow", "SQL", "AWS"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 8500,
                "salary_max": 12500,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Senior Data Scientist",
                "company": "CloudNova AI",
                "description": "Lead modelling projects from problem definition through to production deployment.",
                "required_education": JobPosting.Education.MASTER,
                "required_skills": ["Python", "Machine Learning", "Statistics", "SQL", "Communication"],
                "min_years_experience": 5,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 11000,
                "salary_max": 15500,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Computer Vision Engineer",
                "company": "CloudNova AI",
                "description": "Develop vision models for document parsing and identity verification.",
                "required_education": JobPosting.Education.MASTER,
                "required_skills": ["Python", "OpenCV", "PyTorch", "Computer Vision", "Docker"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Melbourne",
                "salary_min": 10000,
                "salary_max": 14500,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Cloud Infrastructure Engineer",
                "company": "CloudNova AI",
                "description": "Provision and optimise AWS environments for GPU-intensive training workloads.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["AWS", "Terraform", "Linux", "Networking", "Cost Optimisation"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 10000,
                "salary_max": 14000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Backend Engineer (Python/FastAPI)",
                "company": "CloudNova AI",
                "description": "Build high-throughput inference APIs and internal data services.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 8000,
                "salary_max": 12000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Technical Product Manager – AI",
                "company": "CloudNova AI",
                "description": "Define and deliver AI-powered features from discovery through launch.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Product Strategy", "Agile", "Machine Learning", "User Stories", "Analytics"],
                "min_years_experience": 5,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Singapore",
                "salary_min": 10000,
                "salary_max": 14000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Prompt Engineer",
                "company": "CloudNova AI",
                "description": "Design, test, and optimise prompts for LLM-powered product features.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["LLMs", "Python", "Prompt Design", "Evaluation", "Technical Writing"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 7000,
                "salary_max": 10500,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "BI & Reporting Analyst",
                "company": "CloudNova AI",
                "description": "Build self-serve dashboards and automate recurring management reports.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Power BI", "SQL", "Python", "Tableau", "Stakeholder Management"],
                "min_years_experience": 2,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Canberra",
                "salary_min": 6500,
                "salary_max": 9500,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Applied Scientist – Ranking & Retrieval",
                "company": "CloudNova AI",
                "description": "Improve candidate–job matching through learning-to-rank and embedding models.",
                "required_education": JobPosting.Education.MASTER,
                "required_skills": ["Python", "Machine Learning", "Information Retrieval", "PyTorch", "SQL"],
                "min_years_experience": 4,
                "work_mode": JobPosting.WorkMode.HYBRID,
                "location": "Sydney",
                "salary_min": 12000,
                "salary_max": 17000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "Data Governance Analyst",
                "company": "CloudNova AI",
                "description": "Establish data quality standards, lineage tracking, and compliance controls.",
                "required_education": JobPosting.Education.BACHELOR,
                "required_skills": ["Data Governance", "SQL", "Python", "Privacy", "Documentation"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.ON_SITE,
                "location": "Canberra",
                "salary_min": 7500,
                "salary_max": 11000,
            },
            {
                "employer": "recruitment@cloudnova.ai",
                "title": "AI Ethics Researcher",
                "company": "CloudNova AI",
                "description": "Evaluate model fairness, bias, and transparency for responsible AI deployment.",
                "required_education": JobPosting.Education.MASTER,
                "required_skills": ["AI Ethics", "Python", "Machine Learning", "Research", "Communication"],
                "min_years_experience": 3,
                "work_mode": JobPosting.WorkMode.REMOTE,
                "location": "Remote",
                "salary_min": 9000,
                "salary_max": 13000,
            },
        ]

        for item in data:
            employer_email = item.pop("employer")
            job, _ = JobPosting.objects.update_or_create(
                employer=employers[employer_email],
                title=item["title"],
                company=item["company"],
                defaults=item,
            )
            jobs[item["title"]] = job

        return jobs

    def create_applications(self, jobs, candidates):
        data = [
            ("Senior Full-Stack Engineer", "aarav.mehta@example.com"),
            ("Backend API Developer", "liam.tan@example.com"),
            ("Cloud DevOps Engineer", "daniel.park@example.com"),
            ("Frontend React Developer", "sophia.chen@example.com"),
            ("UX/UI Designer", "emily.wong@example.com"),
            ("Junior Web Developer", "noah.smith@example.com"),
            ("Machine Learning Engineer", "olivia.brown@example.com"),
            ("Data Analyst", "maya.kumar@example.com"),
            ("Cybersecurity Analyst", "ethan.nguyen@example.com"),
        ]

        for job_title, candidate_email in data:
            JobApplication.objects.get_or_create(
                job=jobs[job_title],
                candidate=candidates[candidate_email],
            )