/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as EmployerMembershipRouteImport } from './routes/employer.membership'
import { Route as EmployerDashboardRouteImport } from './routes/employer.dashboard'
import { Route as EmployerCandidatesRouteImport } from './routes/employer.candidates'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateMembershipRouteImport } from './routes/candidate.membership'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as EmployerJobsNewRouteImport } from './routes/employer.jobs.new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const EmployerMembershipRoute = EmployerMembershipRouteImport.update({
  id: '/employer/membership',
  path: '/employer/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerDashboardRoute = EmployerDashboardRouteImport.update({
  id: '/employer/dashboard',
  path: '/employer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/employer/candidates',
  path: '/employer/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateMembershipRoute = CandidateMembershipRouteImport.update({
  id: '/candidate/membership',
  path: '/candidate/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerJobsNewRoute = EmployerJobsNewRouteImport.update({
  id: '/employer/jobs/new',
  path: '/employer/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/membership': typeof CandidateMembershipRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/membership': typeof EmployerMembershipRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/membership': typeof CandidateMembershipRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/membership': typeof EmployerMembershipRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/membership': typeof CandidateMembershipRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/dashboard': typeof EmployerDashboardRoute
  '/employer/membership': typeof EmployerMembershipRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/employer/jobs/new': typeof EmployerJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/candidate/dashboard'
    | '/candidate/membership'
    | '/candidate/profile'
    | '/employer/candidates'
    | '/employer/dashboard'
    | '/employer/membership'
    | '/jobs/$jobId'
    | '/employer/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/candidate/dashboard'
    | '/candidate/membership'
    | '/candidate/profile'
    | '/employer/candidates'
    | '/employer/dashboard'
    | '/employer/membership'
    | '/jobs/$jobId'
    | '/employer/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/candidate/dashboard'
    | '/candidate/membership'
    | '/candidate/profile'
    | '/employer/candidates'
    | '/employer/dashboard'
    | '/employer/membership'
    | '/jobs/$jobId'
    | '/employer/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateMembershipRoute: typeof CandidateMembershipRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerDashboardRoute: typeof EmployerDashboardRoute
  EmployerMembershipRoute: typeof EmployerMembershipRoute
  EmployerJobsNewRoute: typeof EmployerJobsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/employer/membership': {
      id: '/employer/membership'
      path: '/employer/membership'
      fullPath: '/employer/membership'
      preLoaderRoute: typeof EmployerMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/dashboard': {
      id: '/employer/dashboard'
      path: '/employer/dashboard'
      fullPath: '/employer/dashboard'
      preLoaderRoute: typeof EmployerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/employer/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/membership': {
      id: '/candidate/membership'
      path: '/candidate/membership'
      fullPath: '/candidate/membership'
      preLoaderRoute: typeof CandidateMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/jobs/new': {
      id: '/employer/jobs/new'
      path: '/employer/jobs/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof EmployerJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateMembershipRoute: CandidateMembershipRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerDashboardRoute: EmployerDashboardRoute,
  EmployerMembershipRoute: EmployerMembershipRoute,
  EmployerJobsNewRoute: EmployerJobsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
